### ISSUE TITLE
WARNING: The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by bloggingninja** [vladiliescu/woofy#1]
on some comics I get a "WARNING: The request was aborted: Could not create SSL/TLS secure channel." error and it doesn't download anything. one example is below.

steps to reproduce:
- put attached def file in the woofy definitions folder
- start Woofy
- Add Comic
- select "Deviants"
- download will say complete without downloading anything and the above mentioned error will be in the log file.

Attached files:
- Log file when I try to do it
[Deviants.txt](https://github.com/vladiliescu/woofy/files/4888301/Deviants.txt)
- definition file I used to download the webcomic. (zipped since Github doesn't let me upload a .def file)
[Deviants.zip](https://github.com/vladiliescu/woofy/files/4888306/Deviants.zip)

**Comment by vladiliescu** [comment]
Hey there, I'll look into it - it might take a little while though, as I don't have a Windows machine available at the moment.

**Comment by bloggingninja** [comment]
If it helps, here are a few more definition files that also present the error (just in case it's something weird with one site)
[definitions.zip](https://github.com/vladiliescu/woofy/files/4949238/definitions.zip)

**Comment by Snaid1** [comment]
I ran into this too. I created a pull request with what seems to be a fix. (at least it's working with the def files I've tried). 
https://github.com/vladiliescu/woofy/pull/2

**Comment by vladiliescu** [comment]
I've released [v1.25](https://github.com/vladiliescu/woofy/releases/tag/1.25) which should fix this, please let me know if it works for you @bloggingninja & @Snaid1

**Comment by Snaid1** [comment]
Works for me :) I have a couple of definitions that seem to be having issues but I'm going to assume I made a mistake in the definition files for now (and none of them are the SSL/TLS issue)

**Comment by bloggingninja** [comment]
It's working for me too. Thanks!
